import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  compress: true,
  poweredByHeader: false,
  reactStrictMode: true,
  images: {
    remotePatterns: [
      {
        protocol: 'https',
        hostname: 'cdn.sanity.io',
        pathname: '/images/**',
      },
      {
        protocol: 'https',
        hostname: 'cdn.sanity.io',
        pathname: '/files/**',
      },
    ],
    formats: ['image/avif', 'image/webp'],
    deviceSizes: [640, 750, 828, 1080, 1200, 1440],
    imageSizes: [16, 32, 48, 64, 96, 128, 256, 384],
    minimumCacheTTL: 604800,
    dangerouslyAllowSVG: true,
    qualities: [75, 80, 90, 95],
  },
  experimental: {
    optimizePackageImports: [
      "lucide-react",
      "framer-motion",
      "swiper",
      "@mui/material",
      "@mui/icons-material",
      "react-icons",
      "gsap",
    ],
    serverSourceMaps: true,
  },
  transpilePackages: ["swiper", "framer-motion", "gsap", "lucide-react"],
  compiler: {
    styledComponents: true,
    removeConsole: process.env.NODE_ENV === 'production',
  },
  async redirects() {
    return [
      { source: '/netsuite/solutions', destination: '/netsuite-products', permanent: true },
      { source: '/netsuite/solutions/core-erp/erp', destination: '/netsuite-erp-solution', permanent: true },
      { source: '/netsuite/solutions/analytics/bi', destination: '/netsuite-business-intelligence', permanent: true },
      { source: '/netsuite/solutions/planning/main', destination: '/netsuite-planning-and-budgeting', permanent: true },
      { source: '/netsuite/solutions/core-erp/accounting', destination: '/netsuite-accounting-services', permanent: true },
      { source: '/netsuite/solutions/project-management/openair', destination: '/netsuite-open-air-solution', permanent: true },
      { source: '/netsuite/solutions/analytics/warehouse', destination: '/netsuite-analytics-warehouse', permanent: true },
      { source: '/netsuite/solutions/core-erp/global-business', destination: '/global-business-management', permanent: true },
      { source: '/netsuite/solutions/specialized/suitesuccess', destination: '/netsuite-suitesuccess', permanent: true },
      { source: '/netsuite/solutions/analytics/ai', destination: '/artificial-intelligence-ai', permanent: true },
      { source: '/netsuite/solutions/customer-management/crm', destination: '/netsuite-crm-solutions', permanent: true },
      { source: '/netsuite/solutions/ecommerce/main', destination: '/netsuite-suite-commerce-site-builder', permanent: true },
      { source: '/netsuite/solutions/why-netsuite/main', destination: '/why-netsuite', permanent: true },
      { source: '/netsuite/solutions/project-management/srp', destination: '/service-resource-planning', permanent: true },
      { source: '/netsuite/solutions/specialized/india-localization', destination: '/india-localization-for-netsuite', permanent: true },
      { source: '/netsuite/solutions/addons', destination: '/netsuite-connector', permanent: true },
      { source: '/netsuite/solutions/addons/india-localization', destination: '/india-localization-for-netsuite', permanent: true },
      { source: '/netsuite/solutions/addons/smart-commission', destination: '/smart-commission-app', permanent: true },
      { source: '/netsuite/solutions/addons/data-backup', destination: '/netsuite-data-backup-solution', permanent: true },
      { source: '/netsuite/solutions/addons/connectors/magento2', destination: '/magento-2-netsuite-connector', permanent: true },
      { source: '/netsuite/solutions/addons/connectors/amazon', destination: '/amazon-netsuite-connector', permanent: true },
      { source: '/netsuite/solutions/addons/connectors/shopify', destination: '/shopify-netsuite-connector', permanent: true },
      // Redirect old /netsuite/industries/ and /netsuite/services/ URLs to clean route group URLs
      { source: '/netsuite/industries/:slug', destination: '/netsuite/:slug', permanent: true },
      { source: '/netsuite/services/:slug', destination: '/netsuite/:slug', permanent: true },
      { source: '/zoho/industries/:slug', destination: '/zoho/:slug', permanent: true },
      { source: '/zoho/services/:slug', destination: '/zoho/:slug', permanent: true },
      // Industry route redirects (old slug → new slug matching agsuitetech.com)
      { source: '/netsuite/software', destination: '/netsuite/software-and-technology', permanent: true },
      { source: '/netsuite/it-services', destination: '/netsuite/it-and-professional-services', permanent: true },
      { source: '/netsuite/wholesale', destination: '/netsuite/wholesale-distribution', permanent: true },
      { source: '/netsuite/advertising-marketing', destination: '/netsuite/advertising-and-digital-marketing-agencies', permanent: true },
      { source: '/netsuite/media', destination: '/netsuite/media-and-publishing', permanent: true },
      { source: '/netsuite/retail', destination: '/netsuite/retail-and-e-commerce', permanent: true },
      { source: '/netsuite/transport', destination: '/netsuite/transportation-and-logistics', permanent: true },
      { source: '/netsuite/telecom', destination: '/netsuite/telecom-industry', permanent: true },
      // Zoho Industry short route redirects
      { source: '/zoho/software', destination: '/zoho/software-and-technology', permanent: true },
      { source: '/zoho/it-services', destination: '/zoho/it-and-professional-services', permanent: true },
      { source: '/zoho/wholesale', destination: '/zoho/wholesale-distribution', permanent: true },
      { source: '/zoho/advertising-marketing', destination: '/zoho/advertising-and-digital-marketing-agencies', permanent: true },
      { source: '/zoho/media', destination: '/zoho/media-and-publishing', permanent: true },
      { source: '/zoho/retail', destination: '/zoho/retail-and-e-commerce', permanent: true },
      { source: '/zoho/transport', destination: '/zoho/transportation-and-logistics', permanent: true },
      { source: '/zoho/telecom', destination: '/zoho/telecom-industry', permanent: true },
      // agsuitetech.com root-level Industry slugs → nested NetSuite industry pages
      { source: '/software-and-technology', destination: '/netsuite/software-and-technology', permanent: true },
      { source: '/it-and-professional-services', destination: '/netsuite/it-and-professional-services', permanent: true },
      { source: '/financial-services', destination: '/netsuite/financial-services', permanent: true },
      { source: '/wholesale-distribution', destination: '/netsuite/wholesale-distribution', permanent: true },
      { source: '/advertising-and-digital-marketing-agencies', destination: '/netsuite/advertising-and-digital-marketing-agencies', permanent: true },
      { source: '/media-and-publishing', destination: '/netsuite/media-and-publishing', permanent: true },
      { source: '/retail-and-e-commerce', destination: '/netsuite/retail-and-e-commerce', permanent: true },
      { source: '/transportation-and-logistics', destination: '/netsuite/transportation-and-logistics', permanent: true },
      { source: '/manufacturing', destination: '/netsuite/manufacturing', permanent: true },
      { source: '/telecom-industry', destination: '/netsuite/telecom-industry', permanent: true },
      // agsuitetech.com root-level Services slugs → nested NetSuite services pages
      { source: '/digital-transformation', destination: '/netsuite/digital-transformation', permanent: true },
      { source: '/integration-services', destination: '/netsuite-integration', permanent: true },
      { source: '/training-services', destination: '/netsuite/training-services', permanent: true },
      { source: '/low-code-application-development', destination: '/netsuite/low-code-application-development', permanent: true },
      { source: '/netsuite/low-code', destination: '/netsuite/low-code-application-development', permanent: true },
      { source: '/zoho/low-code', destination: '/zoho/low-code-application-development', permanent: true },
      { source: '/managed-services', destination: '/netsuite-managed-support', permanent: true },
      // Redirect old NetSuite service URLs to new root-level URLs
      { source: '/netsuite/implementation', destination: '/netsuite-erp-and-crm-implementation', permanent: true },
      { source: '/netsuite/integration-services', destination: '/netsuite-integration', permanent: true },
      { source: '/netsuite/customization', destination: '/netsuite-customization', permanent: true },
      { source: '/netsuite/managed-services', destination: '/netsuite-managed-support', permanent: true },
      { source: '/netsuite/consulting', destination: '/netsuite-consulting', permanent: true },
      // Zoho Redirects
      { source: '/zoho-salesiq-marketing', destination: '/zoho-salesiq-implementation', permanent: true },
      { source: '/zoho-payroll-finance', destination: '/zoho-payroll', permanent: true },
      { source: '/zoho-expense-finance', destination: '/zoho-expense', permanent: true },
      { source: '/zoho/solutions/finance/zoho-payroll', destination: '/zoho-payroll', permanent: true },
      { source: '/zoho/solutions/finance/zoho-expense', destination: '/zoho-expense', permanent: true },
      { source: '/zoho/solutions/finance/zoho-books', destination: '/zoho-books-accounting-software', permanent: true },
      { source: '/zoho/solutions/finance/zoho-inventory', destination: '/zoho-inventory-software', permanent: true },
      { source: '/zoho/solutions/hr/zoho-payroll', destination: '/zoho-payroll', permanent: true },
      { source: '/zoho/solutions/finance/zoho-finance-plus', destination: '/zoho-finance-plus', permanent: true },
      { source: '/zoho/solutions/hr/zoho-expense', destination: '/zoho-expense', permanent: true },
      { source: '/zoho/solutions/email-collab/zoho-mail', destination: '/zoho-mail', permanent: true },
      { source: '/zoho/solutions/email-collab/zoho-workplace', destination: '/zoho-workplace', permanent: true },
      { source: '/zoho/solutions/marketing/zoho-sites', destination: '/zoho-sites', permanent: true },
      { source: '/zoho/solutions/marketing/zoho-social', destination: '/zoho-social-media-management', permanent: true },
      { source: '/zoho/solutions/marketing/zoho-commerce', destination: '/zoho-commerce', permanent: true },
      { source: '/zoho/solutions/marketing/zoho-marketing-automation', destination: '/zoho-marketing-automation', permanent: true },
      { source: '/zoho/solutions/marketing/zoho-marketing-plus', destination: '/zoho-marketing-plus', permanent: true },
      { source: '/zoho/solutions/service/zoho-sales-iq', destination: '/zoho-salesiq-implementation', permanent: true },
      { source: '/zoho/solutions/it-management/zoho-one', destination: '/zoho-one', permanent: true },
      { source: '/zoho/solutions/projects/zoho-projects', destination: '/zoho-projects', permanent: true },
      { source: '/zoho/solutions/projects/zoho-sprints', destination: '/zoho-sprint', permanent: true },
      { source: '/zoho/solutions/dev-platforms/zoho-creator', destination: '/zoho-creator', permanent: true },
      { source: '/zoho/solutions/it-management/zoho-it-management', destination: '/zoho-it-management', permanent: true },
      { source: '/zoho/solutions/sales/zoho-crm', destination: '/zoho-crm', permanent: true },
      { source: '/zoho/solutions/sales/zoho-crm-plus', destination: '/zoho-crm-plus', permanent: true },
      { source: '/zoho/solutions/sales/zoho-bigin', destination: '/zoho-bigin', permanent: true },
      { source: '/zoho/solutions/dev-platforms/zoho-catalyst', destination: '/zoho-catalyst', permanent: true },
      { source: '/zoho/solutions/hr/zoho-people', destination: '/zoho-people', permanent: true },
      { source: '/zoho/solutions/hr/zoho-recruit', destination: '/zoho-recruit-hiring-software', permanent: true },
      { source: '/zoho/solutions/hr/zoho-people-plus', destination: '/zoho-people-plus', permanent: true },
      { source: '/zoho/solutions/service/zoho-desk', destination: '/zoho-desk', permanent: true },
      { source: '/zoho/solutions/service/zoho-fsm', destination: '/zoho-fsm', permanent: true },
      { source: '/zoho/solutions/analytics/zoho-analytics', destination: '/zoho-analytics', permanent: true },
      // Redirect old Zoho service URLs to new clean URLs
      { source: '/zoho/implementation', destination: '/zoho-implementation-and-integration', permanent: true },
      { source: '/zoho/integration-services', destination: '/zoho-integration', permanent: true },
      { source: '/zoho/customization', destination: '/zoho-customization', permanent: true },
      { source: '/zoho/managed-services', destination: '/zoho-support', permanent: true },
      { source: '/zoho/training-services', destination: '/zoho-training-services', permanent: true },
    ];
  },
  async rewrites() {
    return [
      { source: '/zoho-implementation-and-integration', destination: '/zoho/implementation' },
      { source: '/zoho-integration', destination: '/zoho/integration-services' },
      { source: '/zoho-customization', destination: '/zoho/customization' },
      { source: '/zoho-support', destination: '/zoho/managed-services' },
      { source: '/zoho-training-services', destination: '/zoho/training-services' },
    ];
  },
};

export default nextConfig;
