import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  compress: true,
  poweredByHeader: false,
  reactStrictMode: true,
  images: {
    unoptimized: true,
    remotePatterns: [
      {
        protocol: 'https',
        hostname: 'www.agsuitetech.com',
        pathname: '/**',
      },
      {
        protocol: 'https',
        hostname: 'agsuitetech.com',
        pathname: '/**',
      },
      {
        protocol: 'https',
        hostname: 'cdn.sanity.io',
        pathname: '/**',
      },
    ],
    formats: ['image/avif', 'image/webp'],
    deviceSizes: [640, 750, 828, 1080, 1200, 1440],
    imageSizes: [16, 32, 48, 64, 96, 128, 256, 384],
    minimumCacheTTL: 604800,
    dangerouslyAllowSVG: true,
    qualities: [75, 80, 90, 95],
  },
  experimental: {
    optimizePackageImports: [
      "lucide-react",
      "framer-motion",
      "swiper",
      "@mui/material",
      "@mui/icons-material",
      "react-icons",
      "gsap",
    ],
    serverSourceMaps: true,
  },
  transpilePackages: ["swiper", "framer-motion", "gsap", "lucide-react"],
  compiler: {
    styledComponents: true,
    removeConsole: process.env.NODE_ENV === 'production',
  },
  async redirects() {
    return [
      {
        source: '/:path*',
        has: [
          {
            type: 'host',
            value: 'agsuitetech.com',
          },
        ],
        destination: 'https://www.agsuitetech.com/:path*',
        permanent: true,
      },
      { source: '/netsuite/solutions', destination: '/netsuite-products', permanent: true },
      { source: '/default-page', destination: '/netsuite', permanent: true },
      { source: '/default-page.php', destination: '/netsuite', permanent: true },
      { source: '/demo', destination: '/netsuite', permanent: true },
      { source: '/demo.php', destination: '/netsuite', permanent: true },
      { source: '/careers', destination: '/netsuite/careers', permanent: true },
      { source: '/about-us', destination: '/netsuite/about-us', permanent: true },
      { source: '/about-us.php', destination: '/netsuite/about-us', permanent: true },
      { source: '/contact', destination: '/netsuite/contact', permanent: true },
      { source: '/contact-us', destination: '/netsuite/contact', permanent: true },
      { source: '/contact-us.php', destination: '/netsuite/contact', permanent: true },
      { source: '/contact.php', destination: '/netsuite/contact', permanent: true },
      { source: '/zoho/solutions', destination: '/zoho-products', permanent: true },
      { source: '/netsuite/solutions/core-erp/erp', destination: '/netsuite-erp-solution', permanent: true },
      { source: '/netsuite/solutions/analytics/bi', destination: '/netsuite-business-intelligence', permanent: true },
      { source: '/netsuite/solutions/planning/main', destination: '/netsuite-planning-and-budgeting', permanent: true },
      { source: '/netsuite/solutions/core-erp/accounting', destination: '/netsuite-accounting-services', permanent: true },
      { source: '/netsuite/solutions/project-management/openair', destination: '/netsuite-open-air-solution', permanent: true },
      { source: '/netsuite/solutions/analytics/warehouse', destination: '/netsuite-analytics-warehouse', permanent: true },
      { source: '/netsuite/solutions/core-erp/global-business', destination: '/global-business-management', permanent: true },
      { source: '/netsuite/solutions/specialized/suitesuccess', destination: '/netsuite-suitesuccess', permanent: true },
      { source: '/netsuite/solutions/analytics/ai', destination: '/artificial-intelligence-ai', permanent: true },
      { source: '/netsuite/solutions/customer-management/crm', destination: '/netsuite-crm-solutions', permanent: true },
      { source: '/netsuite/solutions/ecommerce/main', destination: '/netsuite-suite-commerce-site-builder', permanent: true },
      { source: '/netsuite/solutions/why-netsuite/main', destination: '/why-netsuite', permanent: true },
      { source: '/netsuite/solutions/project-management/srp', destination: '/service-resource-planning', permanent: true },
      { source: '/netsuite/solutions/project-management/netsuite-srp', destination: '/service-resource-planning', permanent: true },
      { source: '/netsuite/solutions/specialized/india-localization', destination: '/india-localization-for-netsuite', permanent: true },
      { source: '/netsuite/solutions/addons', destination: '/netsuite-connector', permanent: true },
      { source: '/netsuite/solutions/addons/india-localization', destination: '/india-localization-for-netsuite', permanent: true },
      { source: '/netsuite/solutions/addons/smart-commission', destination: '/smart-commission-app', permanent: true },
      { source: '/netsuite/solutions/addons/data-backup', destination: '/netsuite-data-backup-solution', permanent: true },
      { source: '/netsuite/solutions/addons/connectors/magento2', destination: '/magento-2-netsuite-connector', permanent: true },
      { source: '/netsuite/solutions/addons/connectors/amazon', destination: '/amazon-netsuite-connector', permanent: true },
      { source: '/netsuite/solutions/addons/connectors/shopify', destination: '/shopify-netsuite-connector', permanent: true },
      // Redirect old /netsuite/industries/ and /netsuite/services/ URLs to clean route group URLs
      { source: '/netsuite/industries/:slug', destination: '/netsuite/:slug', permanent: true },
      { source: '/netsuite/services/:slug', destination: '/netsuite/:slug', permanent: true },
      { source: '/zoho/industries/:slug', destination: '/zoho/:slug', permanent: true },
      { source: '/zoho/services/:slug', destination: '/zoho/:slug', permanent: true },
      // Industry route redirects (old slug → new slug matching agsuitetech.com)
      { source: '/netsuite/software', destination: '/netsuite/software-and-technology', permanent: true },
      { source: '/netsuite/it-services', destination: '/netsuite/it-and-professional-services', permanent: true },
      { source: '/netsuite/wholesale', destination: '/netsuite/wholesale-distribution', permanent: true },
      { source: '/netsuite/advertising-marketing', destination: '/netsuite/advertising-and-digital-marketing-agencies', permanent: true },
      { source: '/netsuite/media', destination: '/netsuite/media-and-publishing', permanent: true },
      { source: '/netsuite/retail', destination: '/netsuite/retail-and-e-commerce', permanent: true },
      { source: '/netsuite/transport', destination: '/netsuite/transportation-and-logistics', permanent: true },
      { source: '/netsuite/telecom', destination: '/netsuite/telecom-industry', permanent: true },
      // Zoho Industry short route redirects
      { source: '/zoho/software', destination: '/zoho/software-and-technology', permanent: true },
      { source: '/zoho/it-services', destination: '/zoho/it-and-professional-services', permanent: true },
      { source: '/zoho/wholesale', destination: '/zoho/wholesale-distribution', permanent: true },
      { source: '/zoho/advertising-marketing', destination: '/zoho/advertising-and-digital-marketing-agencies', permanent: true },
      { source: '/zoho/media', destination: '/zoho/media-and-publishing', permanent: true },
      { source: '/zoho/retail', destination: '/zoho/retail-and-e-commerce', permanent: true },
      { source: '/zoho/transport', destination: '/zoho/transportation-and-logistics', permanent: true },
      { source: '/zoho/telecom', destination: '/zoho/telecom-industry', permanent: true },
      // agsuitetech.com root-level Industry slugs → nested NetSuite industry pages
      { source: '/software-and-technology', destination: '/netsuite/software-and-technology', permanent: true },
      { source: '/it-and-professional-services', destination: '/netsuite/it-and-professional-services', permanent: true },
      { source: '/financial-services', destination: '/netsuite/financial-services', permanent: true },
      { source: '/wholesale-distribution', destination: '/netsuite/wholesale-distribution', permanent: true },
      { source: '/advertising-and-digital-marketing-agencies', destination: '/netsuite/advertising-and-digital-marketing-agencies', permanent: true },
      { source: '/media-and-publishing', destination: '/netsuite/media-and-publishing', permanent: true },
      { source: '/retail-and-e-commerce', destination: '/netsuite/retail-and-e-commerce', permanent: true },
      { source: '/transportation-and-logistics', destination: '/netsuite/transportation-and-logistics', permanent: true },
      { source: '/manufacturing', destination: '/netsuite/manufacturing', permanent: true },
      { source: '/telecom-industry', destination: '/netsuite/telecom-industry', permanent: true },
      // agsuitetech.com root-level Services slugs → nested NetSuite services pages
      { source: '/digital-transformation', destination: '/netsuite/digital-transformation', permanent: true },
      { source: '/integration-services', destination: '/netsuite-integration', permanent: true },
      { source: '/training-services', destination: '/netsuite/training-services', permanent: true },
      { source: '/low-code-application-development', destination: '/netsuite/low-code-application-development', permanent: true },
      { source: '/netsuite/low-code', destination: '/netsuite/low-code-application-development', permanent: true },
      { source: '/zoho/low-code', destination: '/zoho/low-code-application-development', permanent: true },
      { source: '/managed-services', destination: '/netsuite-managed-support', permanent: true },
      // Redirect old NetSuite service URLs to new root-level URLs
      { source: '/netsuite/implementation', destination: '/netsuite-erp-and-crm-implementation', permanent: true },
      { source: '/netsuite/integration-services', destination: '/netsuite-integration', permanent: true },
      { source: '/netsuite/customization', destination: '/netsuite-customization', permanent: true },
      { source: '/netsuite/managed-services', destination: '/netsuite-managed-support', permanent: true },
      { source: '/netsuite/consulting', destination: '/netsuite-consulting', permanent: true },
      // Zoho Redirects
      { source: '/zoho-salesiq-marketing', destination: '/zoho-salesiq-implementation', permanent: true },
      { source: '/zoho-payroll-finance', destination: '/zoho-payroll', permanent: true },
      { source: '/zoho-expense-finance', destination: '/zoho-expense', permanent: true },
      { source: '/zoho/solutions/finance/zoho-payroll', destination: '/zoho-payroll', permanent: true },
      { source: '/zoho/solutions/finance/zoho-expense', destination: '/zoho-expense', permanent: true },
      { source: '/zoho/solutions/finance/zoho-books', destination: '/zoho-books-accounting-software', permanent: true },
      { source: '/zoho/solutions/finance/zoho-inventory', destination: '/zoho-inventory-software', permanent: true },
      { source: '/zoho/solutions/hr/zoho-payroll', destination: '/zoho-payroll', permanent: true },
      { source: '/zoho/solutions/finance/zoho-finance-plus', destination: '/zoho-finance-plus', permanent: true },
      { source: '/zoho/solutions/hr/zoho-expense', destination: '/zoho-expense', permanent: true },
      { source: '/zoho/solutions/email-collab/zoho-mail', destination: '/zoho-mail', permanent: true },
      { source: '/zoho/solutions/email-collab/zoho-workplace', destination: '/zoho-workplace', permanent: true },
      { source: '/zoho/solutions/marketing/zoho-sites', destination: '/zoho-sites', permanent: true },
      { source: '/zoho/solutions/marketing/zoho-social', destination: '/zoho-social-media-management', permanent: true },
      { source: '/zoho/solutions/marketing/zoho-commerce', destination: '/zoho-commerce', permanent: true },
      { source: '/zoho/solutions/marketing/zoho-marketing-automation', destination: '/zoho-marketing-automation', permanent: true },
      { source: '/zoho/solutions/marketing/zoho-marketing-plus', destination: '/zoho-marketing-plus', permanent: true },
      { source: '/zoho/solutions/service/zoho-sales-iq', destination: '/zoho-salesiq-implementation', permanent: true },
      { source: '/zoho/solutions/it-management/zoho-one', destination: '/zoho-one', permanent: true },
      { source: '/zoho/solutions/projects/zoho-projects', destination: '/zoho-projects', permanent: true },
      { source: '/zoho/solutions/projects/zoho-sprints', destination: '/zoho-sprint', permanent: true },
      { source: '/zoho/solutions/dev-platforms/zoho-creator', destination: '/zoho-creator', permanent: true },
      { source: '/zoho/solutions/it-management/zoho-it-management', destination: '/zoho-it-management', permanent: true },
      { source: '/zoho/solutions/sales/zoho-crm', destination: '/zoho-crm', permanent: true },
      { source: '/zoho/solutions/sales/zoho-crm-plus', destination: '/zoho-crm-plus', permanent: true },
      { source: '/zoho/solutions/sales/zoho-bigin', destination: '/zoho-bigin', permanent: true },
      { source: '/zoho/solutions/dev-platforms/zoho-catalyst', destination: '/zoho-catalyst', permanent: true },
      { source: '/zoho/solutions/hr/zoho-people', destination: '/zoho-people', permanent: true },
      { source: '/zoho/solutions/hr/zoho-recruit', destination: '/zoho-recruit-hiring-software', permanent: true },
      { source: '/zoho/solutions/hr/zoho-people-plus', destination: '/zoho-people-plus', permanent: true },
      { source: '/zoho/solutions/service/zoho-desk', destination: '/zoho-desk', permanent: true },
      { source: '/zoho/solutions/service/zoho-fsm', destination: '/zoho-fsm', permanent: true },
      { source: '/zoho/solutions/analytics/zoho-analytics', destination: '/zoho-analytics', permanent: true },
      // Redirect old Zoho service URLs to new clean URLs
      { source: '/zoho/implementation', destination: '/zoho-implementation-and-integration', permanent: true },
      { source: '/zoho/integration-services', destination: '/zoho-integration', permanent: true },
      { source: '/zoho/customization', destination: '/zoho-customization', permanent: true },
      { source: '/zoho/managed-services', destination: '/zoho-support', permanent: true },
      { source: '/zoho/training-services', destination: '/zoho-training-services', permanent: true },

      // Legacy PHP and Old Site Redirects
      { source: '/NetSuite-Products.php', destination: '/netsuite-products', permanent: true },
      { source: '/netsuite-erp-solution.php', destination: '/netsuite-erp-solution', permanent: true },
      { source: '/netsuite-accounting-services.php', destination: '/netsuite-accounting-services', permanent: true },
      { source: '/Global-Business-Management.php', destination: '/global-business-management', permanent: true },
      { source: '/netsuite-crm-solutions.php', destination: '/netsuite-crm-solutions', permanent: true },
      { source: '/service-resource-planning.php', destination: '/service-resource-planning', permanent: true },
      { source: '/netsuite-suite-commerce-site-builder.php', destination: '/netsuite-suite-commerce-site-builder', permanent: true },
      { source: '/netsuite-open-air-solution.php', destination: '/netsuite-open-air-solution', permanent: true },
      { source: '/netsuite-suitesuccess.php', destination: '/netsuite-suitesuccess', permanent: true },
      { source: '/HCM-Human-Capital-Management.php', destination: '/netsuite-products', permanent: true },
      { source: '/Zoho-Products.php', destination: '/zoho-products', permanent: true },
      { source: '/Zoho-CRM.php', destination: '/zoho-crm', permanent: true },
      { source: '/Zoho-One.php', destination: '/zoho-one', permanent: true },
      { source: '/Zoho-People.php', destination: '/zoho-people', permanent: true },
      { source: '/Zoho-Book.php', destination: '/zoho-books-accounting-software', permanent: true },
      { source: '/Zoho-Inventory-Software.php', destination: '/zoho-inventory-software', permanent: true },
      { source: '/Zoho-Sites.php', destination: '/zoho-sites', permanent: true },
      { source: '/Zoho-Projects.php', destination: '/zoho-projects', permanent: true },
      { source: '/contact-us/thank-you.php', destination: '/thank-you/', permanent: true },
      { source: '/Zoho-Desk.php', destination: '/zoho-desk', permanent: true },
      { source: '/zoho-social-media-management.php', destination: '/zoho-social-media-management', permanent: true },
      { source: '/Zoho-SalesIQ.php', destination: '/zoho-salesiq-implementation', permanent: true },
      { source: '/Zoho-Expense.php', destination: '/zoho-expense', permanent: true },
      { source: '/Zoho-Recruit-Hiring-Software.php', destination: '/zoho-recruit-hiring-software', permanent: true },
      { source: '/AGSuite-Products.php', destination: '/netsuite-connector', permanent: true },
      { source: '/India-Tax-Solution.php', destination: '/india-tax-solution', permanent: true },
      { source: '/Shopify-Netsuite-Connector.php', destination: '/shopify-netsuite-connector', permanent: true },
      { source: '/magento-to-netsuite-connector.php', destination: '/magento-2-netsuite-connector/', permanent: true },
      { source: '/Amazon-NetSuite-Connector.php', destination: '/amazon-netSuite-connector', permanent: true },
      { source: '/Smart-Commission-App.php', destination: '/smart-commission-app', permanent: true },
      { source: '/e-invoice-software.php', destination: '/e-invoice-software', permanent: true },
      { source: '/netsuite-connector.php', destination: '/netsuite-connector', permanent: true },
      { source: '/shopify-development.php', destination: '/shopify-development', permanent: true },
      { source: '/celigo-development.php', destination: '/celigo-development', permanent: true },
      { source: '/Avalara.php', destination: '/avalara', permanent: true },
      { source: '/pipedrive-products.php', destination: '/pipedrive-products', permanent: true },
      { source: '/NetSuite-Services.php', destination: '/netsuite-services/', permanent: true },
      { source: '/NetSuite-ERP-&-CRM-Implementation.php', destination: '/netsuite-erp-and-crm-implementation', permanent: true },
      { source: '/netsuite-suite-commerce-service-provider.php', destination: '/netsuite-suite-commerce-site-builder', permanent: true },
      { source: '/free-consultation-now/thankyou.php', destination: '/thank-you/', permanent: true },
      { source: '/NetSuite-Optimization.php', destination: '/netsuite-crm-solutions', permanent: true },
      { source: '/NetSuite-Customization.php', destination: '/netsuite-customization', permanent: true },
      { source: '/NetSuite-Consulting.php', destination: '/netsuite-consulting', permanent: true },
      { source: '/NetSuite-Administration.php', destination: '/netsuite-products', permanent: true },
      { source: '/netsuite-openair-management-service.php', destination: '/netsuite-open-air-solution', permanent: true },
      { source: '/Netsuite-Training.php', destination: '/training-services', permanent: true },
      { source: '/thankyou.php', destination: '/thank-you/', permanent: true },
      { source: '/Zoho-Services.php', destination: '/zoho-products', permanent: true },
      { source: '/Zoho-Implementation-&-Integration.php', destination: '/zoho-implementation-and-integration', permanent: true },
      { source: '/Zoho-Customization.php', destination: '/zoho-customization', permanent: true },
      { source: '/careers/thankyou.php', destination: '/thank-you/', permanent: true },
      { source: '/Zoho-Support.php', destination: '/zoho-support', permanent: true },
      { source: '/pipedrive-services.php', destination: '/pipedrive-products', permanent: true },
      { source: '/bookkeeping-and-accounting-services.php', destination: '/netsuite-accounting-services', permanent: true },
      { source: '/Wholesale-Distribution.php', destination: '/wholesale-distribution', permanent: true },
      { source: '/Manufacturing.php', destination: '/manufacturing', permanent: true },
      { source: '/Non-Profit.php', destination: '/netsuite-connector', permanent: true },
      { source: '/advertising-media-and-publication.php', destination: '/advertising-and-digital-marketing-agencies', permanent: true },
      { source: '/e-commerceindustry.php', destination: '/retail-and-e-commerce', permanent: true },
      { source: '/professional-IT-services.php', destination: '/it-and-professional-services', permanent: true },
      { source: '/software-and-technology.php', destination: '/software-and-technology', permanent: true },
      { source: '/zoho-bigin-or-zoho-crm-choosing-the-best-option-for-your-business.php', destination: '/blog/zoho-bigin-or-zoho-crm-choosing-the-best-option-for-your-business', permanent: true },
      { source: '/oracle-netsuite-financial-management-fostering-cfo-cio-collaboration-for-strategic-success.php', destination: '/blog/oracle-netsuite-financial-management-fostering-cfo-cio-collaboration-for-strategic-success', permanent: true },
      { source: '/mastering-e-invoicing-in-zoho-books-a-users-guide-to-efficient-billing.php', destination: '/blog/mastering-e-invoicing-in-zoho-books-a-users-guide-to-efficient-billing', permanent: true },
      { source: '/advanced-strategies-for-customizing-netsuite-to-fit-your-business-needs.php', destination: '/blog/advanced-strategies-for-customizing-netsuite-to-fit-your-business-needs', permanent: true },
      { source: '/introducing-zoho-people-plus-now-with-zoho-payrolls-uae-edition.php', destination: '/blog/introducing-zoho-people-plus-now-with-zoho-payrolls-uae-edition', permanent: true },
      { source: '/hubspot-vs-zoho-crm-a-comparison.php', destination: '/blog/hubspot-vs-zoho-crm-a-comparison', permanent: true },
      { source: '/increase-productivity-with-whatsapp-zoho-crm-integration.php', destination: '/blog/increase-productivity-with-whatsapp-zoho-crm-integration', permanent: true },
      { source: '/unlocking-seamless-integration-timelinesai-brings-whatsapp-to-zoho-crm.php', destination: '/blog/unlocking-seamless-integration-timelinesai-brings-whatsapp-to-zoho-crm', permanent: true },
      { source: '/optimizing-your-business-operations-with-netsuite-accounting-software.php', destination: '/blog/optimizing-your-business-operations-with-netsuite-accounting-software', permanent: true },
      { source: '/boost-your-business-efficiency-with-netsuite-accounting-software.php', destination: '/blog/boost-your-business-efficiency-with-netsuite-accounting-software', permanent: true },
      { source: '/best-practices-for-successful-tally-to-zoho-books-data-migration.php', destination: '/blog/best-practices-for-successful-tally-to-zoho-books-data-migration', permanent: true },
      { source: '/is-tally-erp-to-zoho-books-migration-worth-it.php', destination: '/blog/is-tally-erp-to-zoho-books-migration-worth-it', permanent: true },
      { source: '/zoho-payroll-unleashed-transforming-payroll-management-for-modern-businesses.php', destination: '/blog/zoho-payroll-unleashed-transforming-payroll-management-for-modern-businesses', permanent: true },
      { source: '/benefits-of-transitioning-from-tally-to-zoho-books-for-your-business.php', destination: '/blog/benefits-of-transitioning-from-tally-to-zoho-books-for-your-business', permanent: true },
      { source: '/why-netsuite-is-the-ultimate-solution-for-elevating-customer-service.php', destination: '/blog/why-netsuite-is-the-ultimate-solution-for-elevating-customer-service', permanent: true },
      { source: '/personalizing-customer-interactions-zoho-desk-customization.php', destination: '/blog/personalizing-customer-interactions-zoho-desk-customization', permanent: true },
      { source: '/improve-customer-satisfaction-and-retention-with-oracle-netsuite-for-transportation-and-logistics.php', destination: '/blog/improve-customer-satisfaction-and-retention-with-oracle-netsuite-for-transportation-and-logistics', permanent: true },
      { source: '/mastering-financial-control-with-zoho-books.php', destination: '/blog/mastering-financial-control-with-zoho-books', permanent: true },
      { source: '/how-to-integrate-zoho-pagesense-with-zoho-flow-a-step-by-step-guide.php', destination: '/blog/how-to-integrate-zoho-pagesense-with-zoho-flow-a-step-by-step-guide', permanent: true },
      { source: '/simplifying-cash-flow-management-netsuites-solutions-for-business-owners.php', destination: '/blog/simplifying-cash-flow-management-netsuites-solutions-for-business-owners', permanent: true },
      { source: '/the-8-key-features-of-zoho-crm-mobile-app-that-will-change-the-way-you-do-business.php', destination: '/blog/the-8-key-features-of-zoho-crm-mobile-app-that-will-change-the-way-you-do-business', permanent: true },
      { source: '/mergers-and-acquisitions-made-easier-why-private-equity-firms-should-use-netsuite.php', destination: '/blog/mergers-and-acquisitions-made-easier-why-private-equity-firms-should-use-netsuite', permanent: true },
      { source: '/effortless-approvals-made-simple-integrating-zoho-sign-with-zoho-finance-apps.php', destination: '/blog/effortless-approvals-made-simple-integrating-zoho-sign-with-zoho-finance-apps', permanent: true },
      { source: '/navigate-the-complexities-of-global-markets-with-netsuite-global-business-management.php', destination: '/blog/navigate-the-complexities-of-global-markets-with-netsuite-global-business-management', permanent: true },
      { source: '/discover-the-perfect-e-commerce-solution-unleash-the-benefits-of-zoho-shopify-integration-for-your-business.php', destination: '/blog/discover-the-perfect-e-commerce-solution-unleash-the-benefits-of-zoho-shopify-integration-for-your-business', permanent: true },
      { source: '/experience-the-power-of-netsuite-e-commerce-simplify-and-supercharge-your-online-business.php', destination: '/blog/experience-the-power-of-netsuite-e-commerce-simplify-and-supercharge-your-online-business', permanent: true },
      { source: '/simple-steps-to-build-a-visually-stunning-website-with-zoho-sites.php', destination: '/blog/simple-steps-to-build-a-visually-stunning-website-with-zoho-sites', permanent: true },
      { source: '/the-advantages-of-integrating-accounting-software-and-inventory-tracking-into-your-business.php', destination: '/blog/the-advantages-of-integrating-accounting-software-and-inventory-tracking-into-your-business', permanent: true },
      { source: '/Blog-News.php', destination: '/blogs', permanent: true },
      { source: '/about.php', destination: '/about-us', permanent: true },
      { source: '/customer-testimonials.php', destination: '/customer-testimonials', permanent: true },
      { source: '/careers.php', destination: '/careers', permanent: true },
      { source: '/support.php', destination: '/support', permanent: true },
      { source: '/quote-now.php', destination: '/quote-now', permanent: true },
      { source: '/events.php', destination: '/events', permanent: true },
      { source: '/Social-Impact.php', destination: '/social-impact', permanent: true },
      { source: '/FAQ.php', destination: '/faq', permanent: true },
      { source: '/oracle-NetSuite-emerging-solution-provider-west-award.php', destination: '/oracle-netsuite-emerging-solution-provider-west-award/', permanent: true },
      { source: '/New-Feeds.php', destination: '/news-feeds', permanent: true },
      { source: '/Downloads.php', destination: '/downloads', permanent: true },
      { source: '/whitepapers.php', destination: '/whitepapers', permanent: true },
      { source: '/Free-Consultation-Now.php', destination: '/free-consultation', permanent: true },
      { source: '/contact.php', destination: '/contact', permanent: true },
      { source: '/zoho-customer-testimonials.php', destination: '/zoho-products/', permanent: true },
      { source: '/zoho-customer-list.php', destination: '/zoho-products/', permanent: true },
      { source: '/zoho-case-studies.php', destination: '/zoho-products/', permanent: true },
      { source: '/Referral-Partner-Program.php', destination: '/Referral-Partner-Program', permanent: true },
      { source: '/Alliance-Partner-Program.php', destination: '/Alliance-Partner-Program', permanent: true },
      { source: '/netsuite-services.php', destination: '/netsuite-services/', permanent: true },
      { source: '/netsuite-business-intelligence.php', destination: '/netsuite-business-intelligence/', permanent: true },
      { source: '/netsuite/', destination: '/netsuite-products/', permanent: true },
      { source: '/SuiteSuccess-Business-Management-Solution.php', destination: '/netsuite-suitesuccess/', permanent: true },
      { source: '/ERP-System.php', destination: '/netsuite-erp-solution/', permanent: true },
      { source: '/Accounting-Software.php', destination: '/netsuite-accounting-services/', permanent: true },
      { source: '/CRM-software.php', destination: '/netsuite-crm-solutions/', permanent: true },
      { source: '/SRP.php', destination: '/service-resource-planning/', permanent: true },
      { source: '/E-commerce.php', destination: '/netsuite-suite-commerce-site-builder/', permanent: true },
      { source: '/Business-intelligence.php', destination: '/netsuite-business-intelligence/', permanent: true },
      { source: '/Open-Air.php', destination: '/netsuite-open-air-solution/', permanent: true },
      { source: '/Zoho-Social.php', destination: '/zoho-social-media-management/', permanent: true },
      { source: '/Magento-2-NetSuite-Connector.php', destination: '/magento-2-netsuite-connector/', permanent: true },
      { source: '/India-E-Invoicing-Solution.php', destination: '/e-invoice-software/', permanent: true },
      { source: '/terms-and-conditions.php', destination: '/terms-and-conditions/', permanent: true },
      { source: '/why-choose-netsuite-erp-over-other-cloud-erp-platforms.php', destination: '/why-choose-netsuite-erp-over-other-cloud-erp-platforms/', permanent: true },
      { source: '/Other-Products.php', destination: '/netsuite-connector/', permanent: true },
      { source: '/Zoho-Inventory.php', destination: '/zoho-inventory-software/', permanent: true },
      { source: '/Software-&-Professional-Services.php', destination: '/software-and-technology/', permanent: true },
      { source: '/pipedrive-software.php', destination: '/pipedrive-products/', permanent: true },
      { source: '/request-a-quote', destination: '/quote-now/', permanent: true },
      { source: '/contact-us', destination: '/contact/', permanent: true },
      { source: '/netsuite-integration.php', destination: '/netsuite-integration/', permanent: true },
      { source: '/NetSuite-Integration.php', destination: '/netsuite-integration/', permanent: true },
      { source: '/News.php', destination: '/events/', permanent: true },
      { source: '/privacy-policy.php', destination: '/privacy-policy/', permanent: true },
      { source: '/zoho-books/', destination: '/zoho-books-accounting-software/', permanent: true },
      { source: '/e-commerceindustry/', destination: '/retail-and-e-commerce/', permanent: true },
      { source: '/zoho-customisation/', destination: '/zoho-customization/', permanent: true },
      { source: '/zoho-implementation/', destination: '/zoho-implementation-and-integration/', permanent: true },
      { source: '/zoho-sales-iq/', destination: '/zoho-salesiq-implementation/', permanent: true },
      { source: '/zoho-recruit/', destination: '/zoho-recruit-hiring-software/', permanent: true },
      { source: '/zoho-inventory/', destination: '/zoho-inventory-software/', permanent: true },
      { source: '/netsuite-implementation/', destination: '/netsuite-erp-and-crm-implementation/', permanent: true },
      { source: '/zoho/', destination: '/zoho-products/', permanent: true },
      { source: '/professional-it-services/', destination: '/it-and-professional-services/', permanent: true },
      { source: '/other-solutions/', destination: '/netsuite-connector/', permanent: true },
      { source: '/why-should-fast-growing-companies-adopt-netsuite-financials-to-accelerate-growth', destination: '/blog/why-should-fast-growing-companies-adopt-netsuite-financials-to-accelerate-growth/', permanent: true },
      { source: '/software-technology/', destination: '/software-and-technology/', permanent: true },
      { source: '/accounting-software/', destination: '/netsuite-accounting-services/', permanent: true },
      { source: '/advertising-media-publication/', destination: '/advertising-and-digital-marketing-agencies/', permanent: true },
      { source: '/netsuit-managed-support/', destination: '/netsuite-managed-support/', permanent: true },
      { source: '/zoho-releases.php', destination: '/zoho-products/', permanent: true },
      { source: '/zoho-authorized-partner/', destination: '/zoho-products/', permanent: true },
      { source: '/webinar-quickbooks-to-netsuite/', destination: '/', permanent: true },
      { source: '/PipeDrive/', destination: '/pipedrive-products/', permanent: true },
      { source: '/oracle-cloudworld-tour/', destination: '/', permanent: true },
      { source: '/feedback/', destination: '/', permanent: true },
      { source: '/cloud-erp-solution-provider/', destination: '/', permanent: true },
      { source: '/reason-to-choose-Shopify.php', destination: '/blog/reason-to-choose-shopify/', permanent: true },
      { source: '/netsuite-erp.php', destination: '/blog/netsuite-erp/', permanent: true },
      { source: '/why-oracle-netsuite-for-business-management.php', destination: '/blog/why-oracle-netsuite-for-business-management/', permanent: true },
      { source: '/zoho-improvement-and-latest-features.php', destination: '/blog/zoho-improvement-and-latest-features/', permanent: true },
      { source: '/top-reasons-why-netsuite-is-vital-for-your-business-success.php', destination: '/blog/top-reasons-why-netsuite-is-vital-for-your-business-success', permanent: true },
      { source: '/streamline-your-recruitment-process-on-the-go-with-zoho-recruit.php', destination: '/blog/streamline-your-recruitment-process-on-the-go-with-zoho-recruit', permanent: true },
      { source: '/quickbooks-to-zoho-books-migration.php', destination: '/quickbooks-to-zoho-books-migration', permanent: true },
      { source: '/netsuite-erp-implementation-top-tips-to-ensure-success.php', destination: '/netsuite-erp-implementation-top-tips-to-ensure-success', permanent: true },
      { source: '/what-exactly-is-zoho-one-and-how-can-it-benefit-our-business.php', destination: '/what-exactly-is-zoho-one-and-how-can-it-benefit-our-business', permanent: true },
      { source: '/announcement-unused-formula-fields-are-no-longer-computed.php', destination: '/zoho-products/', permanent: true },
      { source: '/Retail.php', destination: '/retail-and-e-commerce/', permanent: true },
      { source: '/india-tax-solution/', destination: '/india-localization-for-netsuite/', permanent: true },
      { source: '/a-comprehensive-guide-how-to-seamlessly-integrate-indiamart-with-zoho-crm.php', destination: '/new-feeds/a-comprehensive-guide-how-to-seamlessly-integrate-indiamart-with-zoho-crm/', permanent: true },
      { source: '/zoho-people-integration-connecting-hr-processes-for-seamless-operations.php', destination: '/blog/zoho-people-integration-connecting-hr-processes-for-seamless-operations/', permanent: true },
      { source: '/boosting-efficiency-integrating-zoho-payroll-with-other-business-tools.php', destination: '/blog/boosting-efficiency-integrating-zoho-payroll-with-other-business-tools/', permanent: true },
      { source: '/blog/discover-the-perfect-e-commerce-solution-unleash-the-benefits-of-zoho-shopify-integration-for-your-business-2/', destination: '/blog/discover-ecommerce-solution-zoho-shopify-integration/', permanent: true },
      { source: '/jobs/e-commerce-manager/', destination: '/careers/', permanent: true },
      { source: '/jobs/seo-specialist/', destination: '/careers/', permanent: true },
      { source: '/jobs/data-analyst/', destination: '/careers/', permanent: true },
      { source: '/careers/thank-you.php', destination: '/thank-you/', permanent: true },
      { source: '/free-consultation-now/thank-you.php', destination: '/thank-you/', permanent: true },
      { source: '/software-and-technology/get-my-free-product-tour.php', destination: '/', permanent: true },
      { source: '/jobs/netsuite-sales-executive', destination: '/careers/netsuite-sales-executive/', permanent: true },
      { source: '/jobs/netsuite-sca-developer', destination: '/careers/netsuite-sca-developer/', permanent: true },
      { source: '/jobs/zoho-sales-executive', destination: '/careers/zoho-sales-executive/', permanent: true },
      { source: '/jobs/netsuite-techno-functional-consultant', destination: '/careers/netsuite-techno-functional-consultant/', permanent: true },
      { source: '/jobs/zoho-functional-consultant', destination: '/careers/zoho-functional-consultant/', permanent: true },
      { source: '/jobs/business-development-manager', destination: '/careers/business-development-manager/', permanent: true },
      { source: '/jobs/zoho-developer', destination: '/careers/zoho-developer/', permanent: true },
      { source: '/jobs/netsuite-technical-consultant', destination: '/careers/netsuite-technical-consultant/', permanent: true },
      { source: '/jobs/netsuite-functional-consultant', destination: '/careers/netsuite-functional-consultant/', permanent: true },
      { source: '/jobs/netsuite-developer', destination: '/careers/netsuite-developer/', permanent: true },
      { source: '/jobs/netsuite-technical-lead-2', destination: '/careers/netsuite-technical-lead/', permanent: true },
      { source: '/jobs/netsuite-technical-lead', destination: '/careers/netsuite-functional-lead/', permanent: true },
      { source: '/home-page/', destination: '/', permanent: true },
    ];
  },
  async rewrites() {
    return [
      { source: '/zoho-implementation-and-integration', destination: '/zoho/implementation' },
      { source: '/zoho-integration', destination: '/zoho/integration-services' },
      { source: '/zoho-customization', destination: '/zoho/customization' },
      { source: '/zoho-support', destination: '/zoho/managed-services' },
      { source: '/zoho-training-services', destination: '/zoho/training-services' },
      { source: '/zoho-products', destination: '/zoho/solutions' },
      { source: '/zoho-products/', destination: '/zoho/solutions' },
    ];
  },
};

export default nextConfig;
